### ISSUE TITLE
directionality & DESeq

### ISSUE THREAD

**Issue by 99fatimagr** [lhe17/nebula#19]
Hi,
Thank you for this package!
I had two quick questions.
1) You mention in the tutorial that "If the number of subjects is very small, methods designed for small sample size (e.g., DESeq2, edgeR) should be used for testing subject-level variables." Is it currently possible to use a DESeq/ edgeR type method within nebula while keeping the mixed model framework of many cells per subject, or is this suggesting to pseudobulk and use DESeq/ edgeR?
2) I wanted to confirm the directionality of results for categorical variables. If the variable name in the summary of the results is logFC_BMI_catcontrol, for example, is that saying the fold change of the control category with respect to the treatment category (in this case backwards of typical)?
Thank you,
Fatima

**Comment by lhe17** [comment]
Hi Fatima,

Thank you for your questions.

"Is it currently possible to use a DESeq/ edgeR type method within nebula
while keeping the mixed model framework of many cells per subject"
No. But indeed, this is a useful feature that we consider adding to
upcoming versions of NEBULA.

"is this suggesting to pseudobulk and use DESeq/ edgeR"
Yes, pseudobulk using DESeq/ edgeR is one option in this case.

"If the variable name in the summary of the results is
logFC_BMI_catcontrol, for example, is that saying the fold change of the
control category with respect to the treatment category (in this case
backwards of typical)?"
Not necessarily. It depends on how the levels of the category variable are
coded in your design matrix. The direction of logFC corresponds to the
level coded by one. For example, if control/case are coded by 1/0,
respectively, in your design matrix, then logFC_BMI_catcontrol gives the
fold change of the control category with respect to the treatment category.

Best regards,
Liang

**Comment by 99fatimagr** [comment]
Thank you!
