### ISSUE TITLE
Error in { : task 15 failed - "objective in x0 returns NA"

### ISSUE THREAD

**Issue by Raghav1881** [lhe17/nebula#24]
Hello! 

Thank you for developing Nebula, it had been working well until I recently split my Seurat object as I wanted to run nebula across clusters. I have split my seurat object across the ident 'subclass_labelDE', and have been getting this error only when I run nebula on each cluster, but works when the object is merged. I was wondering if you're familiar with any reasons this error could occur, as I am not sure where I should look. For context, here is the code I am currently using 

```R
suppressWarnings({
  library(Seurat)
  library(goseq)
  library(dplyr)
  library(org.Mm.eg.db)
  library(nebula)
  library(SingleCellExperiment)
  library(future)
})

plan(strategy = multicore(workers = 48))
setwd('/media/raghav1881/data_8tb/hippo_soupx/')
hip.combined <- readRDS('May24_with_peaks.rds')
DefaultAssay(hip.combined) <- 'RNA'

# Make df for corresponding ident (i.e. get all columns for ca3)
#dfgen <- function(nebdf, ident) {
#  cls <- grepl(ident, names(nebdf), ignore.case = T)
#  data <- nebdf[, ..cls, drop = FALSE]
#  data$gene <- nebdf$gene
#  return(data)
#}

# Split Seurat object based on clusters, then run nebula on each cluster
runNeb <- function(seu_obj, ident) {
  seu_list <- SplitObject(seu_obj, split.by = ident)
  neb_list <- list()
  ident_list <- levels(seu_obj)
  n <- 0
  for (k in seu_list) {
    n <- n + 1
    ei <- data.frame(genotype = k$genotype)
    nbd <- list(counts = GetAssayData(k, slot = 'counts'), pred = ei,
                gid = k$genotype)
    df <- model.matrix(~genotype, data = nbd$pred)
    neb <- nebula(count = nbd$counts, id = nbd$gid, pred = df, ncore = 24, 
                  method = 'HL', cpc = 0.05)
    neb_list[[ident_list[[n]]]] <- neb$summary
  }
  return(neb_list)
}

res <- runNeb(hip.combined, 'subclass_labelDE')

```
Thank you in advance, and I would be more than happy to provide more information.
Raghav

**Comment by lhe17** [comment]
Hi Raghav,

Thank you for your question.

I'm not quite sure, but it might be because you set random effects 
id=nbd$gid to be the same as the fixed-effects variable in nbd$pred. 
They all equal to k$genotype. Here, id should be individual ID, rather 
than genotype.

Best regards,

Liang

**Comment by Raghav1881** [comment]
Hi Liang,

Thanks for the prompt reply and for catching that mistake. I fixed my code as follows: 
```R
suppressWarnings({
  library(Seurat)
  library(goseq)
  library(dplyr)
  library(org.Mm.eg.db)
  library(nebula)
  library(SingleCellExperiment)
  library(future)
})

plan(strategy = multicore(workers = 48))
setwd('/media/raghav1881/data_8tb/hippo_soupx/')
hip.combined <- readRDS('May24_with_peaks.rds')
DefaultAssay(hip.combined) <- 'RNA'

# Split Seurat object based on clusters, then run nebula on each cluster
runNeb <- function(seu_obj, ident) {
  seu_list <- SplitObject(seu_obj, split.by = ident)
  neb_list <- list()
  ident_list <- unique(seu_obj$subclass_labelDE)
  n <- 0
  for (k in seu_list) {
    n <- n + 1
    nbd <- list(counts = GetAssayData(k, slot = 'counts'),
                pred = data.frame(genotype = k$genotype),
                sid = k$sample)
    df <- model.matrix(~genotype, data = nbd$pred)
    neb <- nebula(count = nbd$counts, id = nbd$sid, pred = df, ncore = 24,
                  method = 'HL', cpc = 0.05)
    neb_list[[ident_list[[n]]]] <- neb$summary
  }
  return(neb_list)
}

res <- runNeb(hip.combined, 'subclass_labelDE')
``` 

Unfortunately, I am still getting the same error, except that it is task 4 that is failing. I have also provided traceback if this gives any better information. 

<details>
Error in { : task 4 failed - "objective in x0 returns NA"
        
        7. stop(simpleError(msg, call = expr))

        6. e$fun(obj, substitute(ex), parent.frame(), e$data)
       
        5. (function (obj, ex)
            {
            e <- getDoPar()
            e$fun(obj, substitute(ex), parent.frame(), e$data) ...

        4. do.call(`%dopar%`, list(obj, ex), envir = parent.frame())
        
        3. foreach(i = gid, .combine = "cbind") %dorng% {
            posv = call_posindy(count, i - 1, nind)
            if ((posv$mct * mfs) < 3) {
            ord = 3 ...

        2. nebula(count = nbd$counts, id = nbd$sid, pred = df, ncore = 24,
            method = "HL", cpc = 5e-04)

        1. runNeb(hip.combined, "subclass_labelDE")
</details>
Do you think this could be an error in regards to the Seurat object itself, I'm thinking some error is caused upon splitting my object based on clusters, as nebula works fine when I extract all data from the original merged object. I'm assuming this is an error being raised by some other dependant package, but I am not too familiar with tracing errors in R.

Thank you,

Raghav

**Comment by lhe17** [comment]
Hi Raghav,

I do not think this is an error related to the Seurat object.

I would suggest using tryCatch to pinpoint the cluster that causes the 
error. I guess some "irregular" cluster probably leads to the problem. 
By irregular, I mean, for example, a cluster has cells from only one 
person or all cells in this cluster share the same genotype, etc.

You might also try setting ncore = 1 to see whether this solves your 
problem.

Best regards,

Liang

**Comment by lhe17** [comment]
Hi Raghav,
I've no idea why my previous reply two weeks ago did not show up on this
thread.

I can try to replicate and figure out this issue if you could share the
count matrix of any cluster that failed along with the design matrix and
the individual IDs.

Best regards,
Liang

**Comment by lhe17** [comment]
Hi Raghav,

Thank you for sharing your data.
I replicated the error you reported.
I find that the error arises because the elements in your count matrix are
not counts, but real numbers. Rounding to the integers solves the problem.
neb <- nebula(count = round(neb_lamp5$counts), id = neb_lamp5$sid, pred =
df, ncore = 40, method = 'HL', cpc = 0.05, covariance = T)

I'm just curious. Do you really need 40 cores for this data set? I got the
results within around one minute with only two cores.

Best regards,
Liang

**Comment by Raghav1881** [comment]
Hi Liang,

I'm surprised my original counts matrix has decimal values, I would've never even consider checking this, thank you. 

The ncore = 40 was from the initial analysis across genotypes, and I just quickly copy and pasted my code to use in this small subset.

Also I have made a function in R for Seurat and SingleCellExperiment objects to convert them into the list format you use for nebula. Do you have a development branch for which I could make a pull request (I would be happy to add a section in the vignette as well).

Thank you again for all of your help,
Raghav

**Comment by matanhofree** [comment]
I am getting a similar error when running on count data. I tried rounding which does not help. 

I am running the following (v1.5.1):
 res1 <- nebula(round(data_g$count),data_g$id,pred=data_g$pred,offset=round(data_g$offset),ncore = 20,reml=1,model='NBLMM')

I also tried without offset.

This is the error:
Error in { : task 6976 failed - "objective in x0 returns NA"
In addition: Warning message:
In nlminb(para[1], pql_nbm_gamma_ll, gamma = para[2], betas = betae,  :
  NA/NaN function evaluation

**Comment by lhe17** [comment]
Hi Matan,

Thank you for reporting this error.
I think this is a different error, probably related to 'reml=1'. You might
try 'reml=0' and see whether the error vanishes.
I will appreciate it very much if you could share your data_g object with
me so that I can look into this issue.

Best regards,
Liang

**Comment by matanhofree** [comment]
Hi Liang,

Thank you for the prompt reply. The issue persists with reml=0. 
I am attaching an rds of my data_g object. [error_data_g_t.rds.gz](https://github.com/lhe17/nebula/files/13885128/error_data_g_t.rds.gz)

I only have 3 samples in this test, hence I thought setting reml=0 was recommended. 

Best,
Matan
