### ISSUE TITLE
Modelling interaction with cell types

### ISSUE THREAD

**Issue by AngCamp** [lhe17/nebula#26]
I am reanalyzing an experiment which had ~3k cells sequenced at an average depth of 1.5 million reads.  There were 7 cell types of interest in several conditions.  I am specifically interested in an interaction between the condition and a lable the cells express.  So right now I am analyzing each cell type in separate objects.  The model matrix is as follows:

`dkkl1.nebula.df = model.matrix(~Condition:Label, data=dkkl1_nebula$pred)`

Do you think I could do the following and analyze all the cell types at once?

`dkkl1.nebula.df = model.matrix(~Condition:Label:celltype, data=dkkl1_nebula$pred)`

Some of the replicates only had 6 of the cell types in the interaction of interest.  Will nebula still be able to perform well with this data, or is it just too undersampled?

**Comment by AngCamp** [comment]
Also is it then safe to just run multiple test correction on the p-values of the interaction of interest to determine DEGs?  I have just been removing genes which nebula returns nan's in the pvalues, is that best?

**Comment by lhe17** [comment]
Hi AngCamp,

Yes, I think you can analyze all the cell types at once.
If you have too many variables in dkkl1.nebula.df, it can be undersampled.

Best regards,
Liang

**Comment by lhe17** [comment]
Hi AngCamp,

Yes, you can run multiple test correction on the p-values after removing
genes with nan.

Best regards,
Liang

**Comment by AngCamp** [comment]
Hi I am having an error wih
