### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by z5ouyang** [lhe17/nebula#30]
Hi,
Thanks for developing (open source) a very good tool, we use it a lot!

This is not a bug report, rather a functionality request: Is there a python version available?
We are starting dealing with large datasets the issue raised by R sparse matrix limited to 2^31 non-zero elements.

If this is out of your scope. Please close it.
Thanks again!

**Comment by lhe17** [comment]
Hi 15ouyang,

Thank you for your question.
There is no python version available yet.
I'm not sure whether the following strategy works. For now, you might try
splitting the count matrix by genes to circumvent that limitation. For
example, if you have a count matrix of 20000 genes, you can split it into
10 count matrices, each of which has 200 genes, and run the analysis for
them one by one.

Best regards,
Liang

**Comment by z5ouyang** [comment]
Thanks for the suggestions, and I will close the issue for now.
