### ISSUE TITLE
clarification of the NEBULA result in the direction of regulation

### ISSUE THREAD

**Issue by MANZHAOHUI** [lhe17/nebula#51]
Hi Dr. Liang,
In $summary of the NEBULA result, the column 'logFC_cccontrol' indicates the fold change of case vs. control, correct? To be more specific, if the value is positive, does it mean that the gene is more expressed in case,  or in other words, the gene is upregulated toward the case?
Thank you.

**Comment by lhe17** [comment]
Hi Zhaohui,

It depends on how the case/control status is coded in the column
"cccontrol" in your design matrix. If 1 corresponds to a case and 0 is a
control, then yes, a positive value means that the gene is more expressed
in case.

Best regards,
Liang

**Comment by lhe17** [comment]
Please also see my answer to this previous question.
https://github.com/lhe17/nebula/issues/19

**Comment by MANZHAOHUI** [comment]
Thank you, Liang.

**Comment by MANZHAOHUI** [comment]
resolved
